// Homework assignments mapping by treatment target
export const homeworkAssignments = {
  "Anxiety": [
    "Anxiety Triggers & Patterns Log",
    "Daily Anxiety Intensity Rating Sheet",
    "Anxiety Cycle Worksheet",
    "Worry Thought Log",
    "Cognitive Distortions Identification Worksheet",
    "Worry Tree Worksheet",
    "Avoidance Behaviors Checklist",
    "Safety Behaviors Tracking Sheet",
    "Grounding Techniques Practice Log",
    "Box Breathing Daily Practice Sheet",
    "Mindful Breathing Practice Sheet",
    "Thought Record for Catastrophizing",
    "Challenging Anxious Thoughts Worksheet",
    "Mindfulness Body Scan Journal",
    "Exposure Hierarchy Worksheet",
    "In-Vivo Exposure Practice Log",
    "Interoceptive Exposure Log",
    "Calming Self-Talk Worksheet",
    "Coping Skills Practice Log",
    "Relapse Prevention Plan (Anxiety)",
    "Other Assignment"
  ],
  "Depression": [
    "Daily Mood Tracker",
    "Thought Monitoring Worksheet",
    "Rumination Awareness Log",
    "Low-Energy Activity Log",
    "Behavioral Activation Planner",
    "Enjoyable Activities Scheduling Sheet",
    "Sleep Hygiene Plan",
    "Values Identification for Motivation",
    "Goal-Setting Worksheet",
    "Challenging Unhelpful Thoughts Worksheet",
    "Morning Routine Builder",
    "Evening Reflection Worksheet",
    "Gratitude Journal",
    "Self-Compassion Exercise Sheet",
    "Negative Thought Replacement Worksheet",
    "Energy & Activity Tracking Sheet",
    "Social Connection Worksheet",
    "Healthy Habits Planning Worksheet",
    "Emotion Regulation Practice Sheet",
    "Relapse Prevention Plan (Depression)",
    "Other Assignment"
  ],
  "Stress Management": [
    "Stress Triggers Log",
    "Stress Temperature Scale",
    "Daily Stress Rating Journal",
    "ABC Stress Model Worksheet",
    "Coping Skills Inventory",
    "Time Management Planning Sheet",
    "Progressive Muscle Relaxation Log",
    "Breathing Exercises Practice Log",
    "DBT TIP Skills Tracking Sheet",
    "IMPROVE Distress Tolerance Log",
    "Mindfulness 5-4-3-2-1 Practice",
    "Relaxation Skills Practice Log",
    "Stressful Situations Review Worksheet",
    "Workload Prioritization Worksheet",
    "Personal Boundaries Worksheet",
    "Problem-Solving Worksheet",
    "Self-Care Activity Log",
    "Overwhelm Early-Warning Signs Worksheet",
    "Stress Recovery Plan",
    "Weekly De-Stress Schedule",
    "Other Assignment"
  ],
  "Relationship Issues": [
    "Attachment Style Self-Assessment",
    "Relationship Needs & Expectations Worksheet",
    "Communication Styles Assessment",
    "DEAR MAN Communication Practice",
    "Active Listening Homework",
    "Five Love Languages Reflection",
    "Relationship Boundaries Worksheet",
    "Emotion Regulation in Relationships",
    "Partner Appreciation Exercise",
    "Conflict Resolution Steps Worksheet",
    "Fair Fighting Rules Worksheet",
    "Trust-Building Exercises",
    "Communication Barriers Log",
    "Relationship Values Worksheet",
    "Empathy-Building Worksheet",
    "Emotional Intimacy Exercises",
    "Daily Connection Rituals Tracker",
    "Relationship Stress Triggers Worksheet",
    "Repair Attempts Log",
    "Relationship Goals Worksheet",
    "Other Assignment"
  ],
  "Grief & Loss": [
    "Stages of Grief Reflection Worksheet",
    "Emotions Mapping Sheet",
    "Grief Triggers Log",
    "Memory & Meaning Journal",
    "Letter to the Lost Loved One",
    "Continuing Bonds Worksheet",
    "Loss Narrative Worksheet",
    "Coping with Anniversaries Planner",
    "Self-Care During Grief Checklist",
    "Support Network Identification Sheet",
    "Grief Waves Tracking Log",
    "Rituals & Memorial Activities Planner",
    "Managing Overwhelming Emotions Worksheet",
    "Acceptance & Meaning Worksheet",
    "Healing Milestones Reflection Sheet",
    "Gratitude During Loss Exercise",
    "Personal Strengths in Grief Worksheet",
    "Hope-Building Exercise",
    "Daily Grief Diary",
    "Long-Term Grief Coping Plan",
    "Other Assignment"
  ],
  "Trauma and PTSD": [
    "Window of Tolerance Worksheet",
    "Grounding Strategies Worksheet",
    "SUDS Tracking Sheet",
    "Safe/Calm Place Visualization",
    "Trauma Triggers Log",
    "Identifying Intrusive Thoughts Worksheet",
    "Nightmares & Sleep Disturbance Log",
    "Flashback Response Plan",
    "EMDR Resourcing Homework",
    "Body Sensations Awareness Log",
    "Cognitive Restructuring for Trauma",
    "CPT: Challenging Trauma Beliefs",
    "Avoidance Behaviors Log",
    "Trauma Narrative Worksheet",
    "Emotional Regulation Practice Sheet",
    "Hyperarousal Tracking Log",
    "Self-Soothing Skills Worksheet",
    "Recovery Strengths Reflection Sheet",
    "Behavioral Activation for Trauma",
    "Trauma Relapse Prevention Plan",
    "Other Assignment"
  ],
  "Self-Esteem & Confidence": [
    "Core Beliefs Exploration Worksheet",
    "Strengths Identification Worksheet",
    "I Am… Identity Statements",
    "Positive Affirmations Practice",
    "Self-Compassion Exercises",
    "Inner Critic vs Inner Coach Worksheet",
    "Challenging Negative Self-Talk Worksheet",
    "Values & Purpose Mapping",
    "Compliments & Achievements Log",
    "Confidence Exposure Ladder",
    "Daily Confidence Tracking Sheet",
    "Success Journal",
    "Behavioral Experiments for Confidence",
    "Personal Boundaries Reflection",
    "Assertiveness Practice Worksheet",
    "Fear-vs-Fact Worksheet",
    "Emotion Awareness Worksheet",
    "Support System Mapping",
    "Competence Building Exercises",
    "Long-Term Self-Esteem Plan",
    "Other Assignment"
  ],
  "Addiction and Substance Abuse": [
    "Trigger & Craving Log",
    "Readiness Ruler Worksheet",
    "High-Risk Situations Worksheet",
    "ABC Model for Addictive Behaviors",
    "Habit Replacement Planning Sheet",
    "Coping with Cravings Practice",
    "Urge Surfing Practice Log",
    "Support Network Identification Sheet",
    "Recovery Skills Inventory",
    "Substance Use Patterns Log",
    "Relapse Prevention Plan",
    "Personal Motivation Worksheet",
    "Values vs Addiction Worksheet",
    "Daily Recovery Commitment Log",
    "Identity in Recovery Worksheet",
    "Craving Intensity Tracking",
    "Coping Ahead for Triggers Worksheet",
    "Social Pressure Resistance Worksheet",
    "Emotional Regulation Log",
    "Healthy Lifestyle Planning Worksheet",
    "Other Assignment"
  ],
  "Identity & Self-Exploration": [
    "Identity Mapping Exercise",
    "Personal Strengths & Weaknesses Review",
    "Self-Discovery Journal Prompts",
    "Values Clarification Worksheet",
    "Life Timeline Narrative Exercise",
    "Passion & Purpose Inventory",
    "Role Exploration Worksheet",
    "Authentic Self vs External Expectations Worksheet",
    "Vision Board Planning Worksheet",
    "Core Needs Exploration Worksheet",
    "Personality Exploration Worksheet",
    "Decision-Making Style Worksheet",
    "Future Self Visualization",
    "Identity Conflicts Worksheet",
    "Self-Expression Tracking Log",
    "Personal Growth Plan",
    "Identity Strengths & Resources Worksheet",
    "Identity in Relationships Worksheet",
    "Life Direction Reflection Sheet",
    "Self-Acceptance Worksheet",
    "Other Assignment"
  ],
  "Family & Parenting Issues": [
    "Parenting Styles Assessment",
    "Family Communication Patterns Worksheet",
    "Family Roles Exploration Worksheet",
    "Emotion Coaching Worksheet",
    "Co-Parenting Communication Plan",
    "Parent Stress Log",
    "Routine & Structure Planner",
    "Positive Parenting Skills Practice",
    "Child Behavior Log",
    "Boundaries in Family Systems Worksheet",
    "Family Meetings Planner",
    "Praise & Reinforcement Practice",
    "Parent-Child Bonding Activities Tracker",
    "Discipline Consistency Worksheet",
    "Parenting Strengths Worksheet",
    "Parenting Values Worksheet",
    "Family Stress Triggers Log",
    "Conflict Resolution in Families Worksheet",
    "Support System Mapping for Parents",
    "Family Well-Being Plan",
    "Other Assignment"
  ],
  "Work & Career Issues": [
    "Work Stress Log",
    "Burnout Assessment Checklist",
    "Imposter Syndrome Thought Record",
    "Values at Work Worksheet",
    "Productivity & Time Management Planner",
    "Conflict at Work Worksheet",
    "Assertive Communication Practice",
    "Work-Life Balance Tracker",
    "Leadership & Confidence Inventory",
    "Career Goals Clarification Sheet",
    "Skills Development Plan",
    "Weekly Accomplishments Log",
    "Stressful Situations Review",
    "Communication Barriers Log",
    "Task Prioritization Worksheet",
    "Strengths in Workplace Worksheet",
    "Job Satisfaction Reflection Sheet",
    "Difficult Conversations Practice",
    "Workplace Triggers Log",
    "Career Decision-Making Worksheet",
    "Other Assignment"
  ],
  "Chronic Illness & Health Concerns": [
    "Symptoms & Pain Log",
    "Activity/Symptom Correlation Log",
    "Stress & Health Triggers Worksheet",
    "Pacing & Energy Budget Worksheet",
    "Self-Care Plan for Chronic Illness",
    "Acceptance & Commitment Worksheet",
    "Grief Around Health Changes Worksheet",
    "Medical Self-Advocacy Worksheet",
    "Sleep Quality Tracking Sheet",
    "Mind-Body Connection Reflection Sheet",
    "Fatigue Tracking Log",
    "Medication Adherence Log",
    "Body Awareness Log",
    "Thought Record for Health Anxiety",
    "Daily Wellness Rituals Planner",
    "Illness Adjustment Reflection",
    "Support System Mapping",
    "Healthy Habits Planner",
    "Coping with Flare-Ups Worksheet",
    "Long-Term Health Maintenance Plan",
    "Other Assignment"
  ],
  "Anger Management": [
    "Anger Triggers Log",
    "Anger Temperature Scale Worksheet",
    "ABC Anger Model Worksheet",
    "De-escalation Skills Practice",
    "Time-Out & Cool-Down Strategy Plan",
    "Opposite Action Log",
    "Cognitive Distortion Tracking",
    "Assertive Expression Practice",
    "Consequence Awareness Worksheet",
    "Anger Patterns & Early Warning Signs Log",
    "Emotional Regulation Log",
    "Conflict De-Brief Worksheet",
    "Communication Skills Practice",
    "Problem-Solving Worksheet",
    "Trigger Situations Reflection Sheet",
    "Anger Narrative Worksheet",
    "Relaxation Practice Log",
    "Self-Talk Replacement Worksheet",
    "Impulse Control Worksheet",
    "Anger Relapse Prevention Plan",
    "Other Assignment"
  ],
  "Eating Disorders & Body Image": [
    "Food & Mood Journal",
    "Hunger/Fullness Awareness Log",
    "Trigger Situations Worksheet",
    "Negative Body Thoughts Tracking",
    "Body Image Reflections Worksheet",
    "Self-Compassion for Eating Worksheet",
    "Values-Based Eating Worksheet",
    "Meal Planning & Routine Sheet",
    "Coping Skills for Urges Worksheet",
    "Body Appreciation Exercise",
    "Eating Patterns Log",
    "Body Checking Reduction Log",
    "Craving Log",
    "Emotional Eating Awareness Worksheet",
    "Eating Rituals Tracking",
    "Satisfied-Hunger Practice Log",
    "Distress Tolerance for Eating Urges",
    "Body Kindness Planning Worksheet",
    "Nutrition Accountability Worksheet",
    "Long-Term Recovery Plan",
    "Other Assignment"
  ],
  "Life Transitions": [
    "Change Impact Assessment Worksheet",
    "Feelings About Change Journal",
    "Identity in Transition Mapping Worksheet",
    "Support Systems Worksheet",
    "Past Transitions Reflection",
    "Goals for the Next 30 Days Worksheet",
    "Coping Skills Inventory",
    "Daily Routines Planner",
    "Values Clarification Worksheet",
    "New Habits Planning Sheet",
    "Meaning-Making Worksheet",
    "Life Reorganization Plan",
    "Stress Triggers During Change Log",
    "Emotion Awareness Worksheet",
    "Personal Strengths in Transition",
    "Future Vision Worksheet",
    "Life Planning Journal",
    "Adaptation Success Log",
    "Role Changes Reflection Sheet",
    "Long-Term Adjustment Plan",
    "Other Assignment"
  ],
  "Coping with Disability": [
    "Disability Adjustment Reflection Sheet",
    "Strengths & Abilities Inventory",
    "Emotional Processing Worksheet",
    "Accessibility Needs Checklist",
    "Pacing & Fatigue Log",
    "Self-Advocacy Skills Practice",
    "Support Network Identification Worksheet",
    "Values-Based Living Worksheet",
    "Daily Adaptation Success Log",
    "Identity & Disability Narrative Worksheet",
    "Stress & Coping Log",
    "Energy Management Worksheet",
    "Health Communication Log",
    "Wellness Routines Planner",
    "Activity Adaptation Worksheet",
    "Environmental Barriers Worksheet",
    "Problem-Solving Worksheet",
    "Coping Skills Practice Sheet",
    "Acceptance Worksheet",
    "Future Planning Worksheet",
    "Other Assignment"
  ]
};

// Get homework assignments for a specific treatment target
export const getHomeworkAssignments = (treatmentTarget) => {
  if (!treatmentTarget) return [];
  return homeworkAssignments[treatmentTarget] || [];
};

