version: '3.8'

services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mindbridge-server
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./server/#Environment Configuration.env
    volumes:
      - uploads_data:/app/uploads
    networks:
      - mindbridge-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mindbridge-client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - mindbridge-network
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/hello"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mindbridge-network:
    driver: bridge

volumes:
  uploads_data: 